//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.10 at 11:16:24 dop. CEST 
//


package rph.reversi.ontology;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="playgroundSize" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="player1" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="player2" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="numberOfGames" type="{http://www.w3.org/2001/XMLSchema}int" default="10" />
 *       &lt;attribute name="moveHighlightDelay" type="{http://www.w3.org/2001/XMLSchema}int" default="700" />
 *       &lt;attribute name="moveDelay" type="{http://www.w3.org/2001/XMLSchema}int" default="500" />
 *       &lt;attribute name="gameDelay" type="{http://www.w3.org/2001/XMLSchema}int" default="4000" />
 *       &lt;attribute name="windowLeft" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="windowTop" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="windowWidth" type="{http://www.w3.org/2001/XMLSchema}int" default="600" />
 *       &lt;attribute name="windowHeight" type="{http://www.w3.org/2001/XMLSchema}int" default="450" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Configuration")
public class Configuration {

    @XmlAttribute(required = true)
    protected int playgroundSize;
    @XmlAttribute(required = true)
    protected String player1;
    @XmlAttribute(required = true)
    protected String player2;
    @XmlAttribute
    protected Integer numberOfGames;
    @XmlAttribute
    protected Integer moveHighlightDelay;
    @XmlAttribute
    protected Integer moveDelay;
    @XmlAttribute
    protected Integer gameDelay;
    @XmlAttribute
    protected Integer windowLeft;
    @XmlAttribute
    protected Integer windowTop;
    @XmlAttribute
    protected Integer windowWidth;
    @XmlAttribute
    protected Integer windowHeight;

    /**
     * Gets the value of the playgroundSize property.
     * 
     */
    public int getPlaygroundSize() {
        return playgroundSize;
    }

    /**
     * Sets the value of the playgroundSize property.
     * 
     */
    public void setPlaygroundSize(int value) {
        this.playgroundSize = value;
    }

    /**
     * Gets the value of the player1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlayer1() {
        return player1;
    }

    /**
     * Sets the value of the player1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlayer1(String value) {
        this.player1 = value;
    }

    /**
     * Gets the value of the player2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlayer2() {
        return player2;
    }

    /**
     * Sets the value of the player2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlayer2(String value) {
        this.player2 = value;
    }

    /**
     * Gets the value of the numberOfGames property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getNumberOfGames() {
        if (numberOfGames == null) {
            return  10;
        } else {
            return numberOfGames;
        }
    }

    /**
     * Sets the value of the numberOfGames property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfGames(Integer value) {
        this.numberOfGames = value;
    }

    /**
     * Gets the value of the moveHighlightDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMoveHighlightDelay() {
        if (moveHighlightDelay == null) {
            return  700;
        } else {
            return moveHighlightDelay;
        }
    }

    /**
     * Sets the value of the moveHighlightDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMoveHighlightDelay(Integer value) {
        this.moveHighlightDelay = value;
    }

    /**
     * Gets the value of the moveDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMoveDelay() {
        if (moveDelay == null) {
            return  500;
        } else {
            return moveDelay;
        }
    }

    /**
     * Sets the value of the moveDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMoveDelay(Integer value) {
        this.moveDelay = value;
    }

    /**
     * Gets the value of the gameDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getGameDelay() {
        if (gameDelay == null) {
            return  4000;
        } else {
            return gameDelay;
        }
    }

    /**
     * Sets the value of the gameDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGameDelay(Integer value) {
        this.gameDelay = value;
    }

    /**
     * Gets the value of the windowLeft property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getWindowLeft() {
        if (windowLeft == null) {
            return  0;
        } else {
            return windowLeft;
        }
    }

    /**
     * Sets the value of the windowLeft property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWindowLeft(Integer value) {
        this.windowLeft = value;
    }

    /**
     * Gets the value of the windowTop property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getWindowTop() {
        if (windowTop == null) {
            return  0;
        } else {
            return windowTop;
        }
    }

    /**
     * Sets the value of the windowTop property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWindowTop(Integer value) {
        this.windowTop = value;
    }

    /**
     * Gets the value of the windowWidth property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getWindowWidth() {
        if (windowWidth == null) {
            return  600;
        } else {
            return windowWidth;
        }
    }

    /**
     * Sets the value of the windowWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWindowWidth(Integer value) {
        this.windowWidth = value;
    }

    /**
     * Gets the value of the windowHeight property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getWindowHeight() {
        if (windowHeight == null) {
            return  450;
        } else {
            return windowHeight;
        }
    }

    /**
     * Sets the value of the windowHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWindowHeight(Integer value) {
        this.windowHeight = value;
    }

}
